/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AgoraJavaRecording_AgoraJavaEventHandler */

#ifndef _Included_AgoraJavaRecording_AgoraJavaEventHandler
#define _Included_AgoraJavaRecording_AgoraJavaEventHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
