/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Agora_Recording_AgoraJavaRecording */

#ifndef _Included_com_Agora_Recording_AgoraJavaRecording
#define _Included_com_Agora_Recording_AgoraJavaRecording
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Agora_Recording_AgoraJavaRecording
 * Method:    createChannel
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILcom/Agora/common/RecordingConfig;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Agora_Recording_AgoraJavaRecording_createChannel
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jobject);

/*
 * Class:     com_Agora_Recording_AgoraJavaRecording
 * Method:    leaveChannel
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Agora_Recording_AgoraJavaRecording_leaveChannel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_Agora_Recording_AgoraJavaRecording
 * Method:    setVideoMixingLayout
 * Signature: (JLcom/Agora/common/Common/VideoMixingLayout;)I
 */
JNIEXPORT jint JNICALL Java_com_Agora_Recording_AgoraJavaRecording_setVideoMixingLayout
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_Agora_Recording_AgoraJavaRecording
 * Method:    startService
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_Agora_Recording_AgoraJavaRecording_startService
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_Agora_Recording_AgoraJavaRecording
 * Method:    stopService
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_Agora_Recording_AgoraJavaRecording_stopService
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_Agora_Recording_AgoraJavaRecording
 * Method:    getProperties
 * Signature: (J)Lcom/Agora/common/RecordingEngineProperties;
 */
JNIEXPORT jobject JNICALL Java_com_Agora_Recording_AgoraJavaRecording_getProperties
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
